### ISSUE TITLE
How can I contact you?

### ISSUE THREAD

**Issue by raduprv** [JulianSchroden/cine_remote#1]
Hello.
Sorry for opening an issue, but I would like to get in touch with you, and there was no contact info on your blog.
I read your blog and found it very useful. I am trying to get my Canon M3 to shoot remotely from an ESP32,  and as you know, info about PTP is scarce, and info about Canon specific stuff is even more scarce. I read quite a bit of stuff online, but your blog had the most clear explanations. Unfortunately, I couldn't get my Canon M3 to actually shoot, it returns a camera busy (0x2019). I guess the issue is that I can't get it to switch to shoot/live view mode.
I also wanted to point out that you have a few small errors in your blog: https://julianschroden.com/post/2023-05-10-pairing-and-initializing-a-ptp-ip-connection-with-a-canon-eos-camera/
In  Activate RemoteMode and Activate EventMode you have the operation incorrectly described as int32 instead of int16.

Anyway, the project I am working at might be of some interest to you, so if you are interested, please let me know how I can get in touch with you.

**Comment by JulianSchroden** [comment]
Hi,
thanks for reaching out and for reporting the errors.

It's great to hear you are also working on a PTP project. Writing a PTP library for the ESP32 is on my to-do list, too, although during the recent months, I have been working on different side projects. 

Feel free to contact me through [LinkedIn](https://www.linkedin.com/in/julian-schroden/) or using my newly created contact address: contact@julianschroden.com

**Comment by raduprv** [comment]
Great, thanks, I've sent you an e-mail!

**Comment by raduprv** [comment]
Hello,
I sent you a few e-mails, did you get them? I found a few more things about the Canon specific ptp/ip  protocol you might want to add to your article to make it work with more cameras.

**Comment by atmosfar** [comment]
Hi guys, I'm also interested in using an ESP32 for comms with a C100ii, did you get anywhere with this?

**Comment by JulianSchroden** [comment]
Hi @atmosfar 

I haven’t tried controlling my C100II with an ESP32, but since the API uses HTTP, it should be possible.

I’ve put together a blog series where I document the C100II API: https://julianschroden.com/series/Exploring-the-Canon-Browser-Remote-API/1/

**Comment by atmosfar** [comment]
Hi @JulianSchroden I have read your blog with plenty of interest, thank you for doing that work!

I managed to get this working with a Pi Zero and USB ethernet adaptor, at least on a different Wifi AP mode camera. I assume the process will work the same on the Canon. Looking forward to trying it out with Bitfocus Companion to adjust focus remotely from our recording booth.

From memory, these were the steps:
- connect Pi ethernet to your router
- connect Pi wifi to the camera with wpa_supplicant
- setup static route on router to forward requests to the camera IP (192.168.54.1) to Pi (192.168.1.2)
- setup iptables rule on Pi to forward requests to camera
